### ISSUE TITLE
partial results are not shown

### ISSUE THREAD

**Issue by mjaghouri** [AMCeScience/docking-gateway#10]
Check the project FTO-HMBD-50

**Comment by Flythe** [comment]
added, the curl needs a fix though will you look at that?

**Comment by mjaghouri** [comment]
Clicking button "Get Partial Results" says "Hello World!"

**Comment by Flythe** [comment]
'oops', is the graph showing though?

**Comment by mjaghouri** [comment]
the graph was shown. although without the ability to choose a percentage to
download, I wonder what is the use of showing the graph...

On Thu, Jan 15, 2015 at 7:35 PM, Allard van Altena <notifications@github.com

**Comment by Flythe** [comment]
fixed
