### ISSUE TITLE
Update and Refresh button need to be clicked twice 

### ISSUE THREAD

**Issue by sararkd** [AMCeScience/docking-gateway#2]
This happens for the Dirac gateway, both for the 'Update' button on the 'In Process' page and for the 'Refresh' button on the 'Admin' page. 
@mjaghouri, @Flythe, I'm not sure which one of you can fix this, and maybe it's fixed in the next upgrade of the system, but we stil;l have this right now.

**Comment by Flythe** [comment]
added a refresh all button to the admin interface, @mjaghouri will you add a update for a single processing? If not this can be closed.

**Comment by Flythe** [comment]
No more functions will be added to the API anymore so the refresh all button is all we are adding for now
