### ISSUE TITLE
space in project name

### ISSUE THREAD

**Issue by mjaghouri** [AMCeScience/docking-gateway#9]
On docking-dev, having spaces in project names causes trouble. I think this is because the folder name will have spaces and somehow the HTTP-download script (or in fact CURL) fails to download.
Maybe replacing those spaces with %20 solves the issue.

**Comment by Flythe** [comment]
can you test now, spaces in the url are being escaped to %20 now and as far as I can tell the processing manager is uploading the files fine.

**Comment by Flythe** [comment]
should be fixed now
